server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: citizen-service
        uri: lb://citizen-service
        predicates:
        - Path=/citizen/**
      - id: vaccinationcenter-service
        uri: lb://vaccinationcenter-service
        predicates:
        - Path=/vaccinationcenter/**
        



